version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
      - /mnt/uploads:/uploads
    command: node src/app.js
    ports:
      - "3001:3000"
    environment:
      DEBUG: nodejs-docker-express:*
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      API_USERNAME: ${API_USERNAME}
      API_PASSWORD: ${API_PASSWORD}
      API_TOKEN_SECRET: ${API_TOKEN_SECRET}
    networks:
      - blogNetwork
      
networks:
  blogNetwork:
    name: blog_network