version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
      - /uploads:/mnt/uploads
    command: node app.js
    ports:
      - "3001:3000"
    environment:
      DEBUG: nodejs-docker-express:*
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - blogNetwork
      
networks:
  blogNetwork:
    name: blog_network